[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://nuojojauxunveyulriwl.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51b2pvamF1eHVudmV5dWxyaXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0Mjg2MzMsImV4cCI6MjA0NzAwNDYzM30.uIqXSsYWGOFWeEh81_DeLzbklZRuU4uAnfqSxmZt-nU"